### ISSUE TITLE
organize imports is not working

### ISSUE THREAD

**Issue by prowei** [spring-projects/spring-ide#160]
organize imports is not working，3.8.4 is ok

**Comment by martinlippert** [comment]
how did you solve this on your end, in case this happens for other users, too. Would be great if you could share some details. Thanks!!!

**Comment by martinlippert** [comment]
I tried this with a fresh Eclipse Oxygen JEE package install, created a new workspace, new java project, my class -> Organize Imports is bound to the usual keys.

I installed a fresh STS 3.9.0 distro (on 4.7), created a new workspace, new java project, new class -> Organize Imports is not bound to the usual keys anymore (at least not showing up as such in the context menu of the java editor).

The key bindings in the preferences are exactly the same for "Organize Imports" and are defined for both.

We need to find out what additional plugin maybe (or whatever) is causing this, it is a really annoying bug.

**Comment by marcolafranca** [comment]
I also have to confirm the presence of this annoying bug. Only the editor is affected, from the package explorer CTRL+SHIFT+O works as expected.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

This is caused by a keybinding definition in one of the Eclipse plugins that we use (lsp4e). Investigating options and workarounds at the moment.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

here is how you can fix that issue:

- go to the `Preferences -> General -> Keys`
- press `Filters...` and de-select `Filter uncategorized commands`
- look for the command `Go To Symbol in File` and select that
- press `unbind` and `Apply and Close`

Then you get the organize imports keyboard shortcut back

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

There is a change in LSP4E now that changes the binding of the `Go To Symbol in File` command to something different, but it introduces a change to the binding for the `Open Type` command that makes this fix not yet consumable for us in STS.

**Comment by 66wei** [comment]
I just Reference format's configuration，change the **when**  from “In Windows” to "Editing Java Source"，then "Organize Imports" works ok

**Comment by sumit-mundra** [comment]
I also faced the same issue. I solved this by adding a new Key binding with "when javascript view -> organize imports" as template and copying the same for "editing java". I use cmd + shift + O from both package explorer ( single key organize import for all src/main/java ) and also while code editing. So, I can not let go "In Windows" altogether.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

worked on the fixes in LSP4E and everything is merged now.

**Comment by martinlippert** [comment]
This is fixed in LSP4E now, so STS 3.9.1 will pick up this fixed version.

**Comment by gpborla** [comment]
@martinlippert I'm still having the bug in eclipse oxygen. The **when** is set to "Editing Java Source" only.

When I press CTRL SHIFT O, a "0 import added" appears in the bottom left of Eclipse.

Have you encountered same?

**Comment by rougou** [comment]
I'm having the same problem all of a sudden. Organize imports does nothing even when clicking from the Source menu.
Version: Oxygen.2 Release (4.7.2)
Build id: 20171218-0600

**Comment by rougou** [comment]
@gpborla 
I should add I originally installed eclipse 4.7.0 or 4.7.1 and upgraded to 4.7.2.
I just did a clean install of 4.7.2 and imports seem to be working now.

**Comment by gpborla** [comment]
@rougou Spring IDE? I though we're both using Eclipse Oxygen.2 Release (4.7.2)

I'll try to do a clean install like you did when I have the time.

Will keep you posted.

**Comment by gpborla** [comment]
@rougou I didn't do a clean install of Eclipse Java EE Oxygen.2 Release (4.7.2) but I created a new project with a different framework, Spring Boot.

CTRL + SHIFT +O worked fine.

It doesn't work with my project created using Spark Java though.

A weird bug.

**Comment by alevele3** [comment]
I recently installed Eclipse Oxygen Eclipse Java EE IDE for Web Developers.
Version: Oxygen.2 Release (4.7.2)
Build id: 20171218-0600
OS: Mac OS X, v.10.13.3, x86_64 / cocoa
The package import does not work, nor the CTRL + SHFT + O.

**Comment by rougou** [comment]
@gpborla
> @rougou Spring IDE? I though we're both using Eclipse Oxygen.2 Release (4.7.2)

Spring IDE is a plugin for eclipse, and you happen to be posting in their issues. So I just wanted to point out that it seems like an issue with plain Eclipse.
